#define DANCE_TARGET_MOUTH "mouth"
#define DANCE_TARGET_THROAT "throat"
#define DANCE_TARGET_DANCERESS "danceress"
#define DANCE_TARGET_DANCOR "dancor"
#define DANCE_TARGET_HAND "hand"
#define DANCE_TARGET_CHEST "chest"
#define DANCING_FACE_WITH_DANCOR "facedancor"
#define DANCING_FACE_WITH_FEET "facefeet"
#define DANCING_MOUTH_WITH_FEET "mouthfeet"
#define DANCE_TO_FACE "danceface"
#define THIGH_DANCE "thighs"

#define WHITELISTEXRPFILE "[global.config.directory]/whitelist_exrp.txt"
